### PR TITLE
EUI-5864: Activate a newly registered organisation.

### PR DESCRIPTION
**Pull request by rtiru-hmcts**
This commit contains the following changes.
    1. Created a new folder feature_ver2.0 to cater to new approve org design.
    2. Incorporated Login change done as part of tests/EUI-5862-LoginLogout branch.
    3. Added all necesary steps, features and pageobjects under feature_ver_2.0.
    4. Created a new entry in package.json and conf file to run 2.0 tests.

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
[EUI-5864](https://tools.hmcts.net/jira/browse/EUI-5864)

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

### Console Log ###
```
Rohiths-Air:rpx-xui-approve-org rohithtiru$ HMCTS_EMAIL=rohith.tiru1@hmcts.net  HMCTS_PASSWORD=************ TEST_URL=https://administer-orgs.demo.platform.hmcts.net/  yarn run test:2.0:smoke
yarn run v1.22.18
warning package.json: "dependencies" has dependency "mochawesome" with range "^4.1.0" that collides with a dependency in "devDependencies" of the same name with version "3.1.1"
warning ../../../../package.json: No license field
$ protractor ./test/e2e/config/smoke_2.0.conf.js
[15:25:21] I/launcher - Running 1 instances of WebDriver
[15:25:21] I/direct - Using ChromeDriver directly...
(node:56691) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
@2.0_test @fullfunctional @approve_org
Feature: Approve New Organisation

  @2.0_test @fullfunctional @approve_org
  Scenario: Approve New Organisation
    When I navigate to EUI Approve Organisation Url
15:25:25 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #i0116)
15:25:25 GMT+0100 (British Summer Time) : wait done for sec50
15:25:26 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #i0118)
15:25:27 GMT+0100 (British Summer Time) : wait done for sec50
15:25:27 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #idSIButton9)
15:25:28 GMT+0100 (British Summer Time) : wait done for sec50
15:25:30 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:25:31 GMT+0100 (British Summer Time) : wait done for sec50
15:25:31 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:25:31 GMT+0100 (British Summer Time) : wait done for sec50
    Given I am logged into approve organisation with HMCTS admin
15:25:31 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:25:31 GMT+0100 (British Summer Time) : wait done for sec50
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 1
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 1
    Then I should be redirected to approve organisation dashboard page
15:25:37 GMT+0100 (British Summer Time) : Started step
15:25:43 GMT+0100 (British Summer Time) : browser readyState value  "complete"
15:25:43 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(xpath, //a[@class='hmcts-header__link'])
15:25:43 GMT+0100 (British Summer Time) : wait done for sec50
    Then I Check the home page title appear
15:25:43 GMT+0100 (British Summer Time) : Started step
15:25:43 GMT+0100 (British Summer Time) : Completed LONG DELAY
15:25:43 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #main-content h1)
15:25:43 GMT+0100 (British Summer Time) : wait done for sec50
    When I click first organization view link
15:25:43 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-table tr)
15:25:43 GMT+0100 (British Summer Time) : wait done for sec50
    Then I see "Approve organisation" on organisation details page
15:25:44 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #content app-org-details-info h1)
15:25:45 GMT+0100 (British Summer Time) : wait done for sec50
15:25:45 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-summary-list__key)
15:25:45 GMT+0100 (British Summer Time) : wait done for sec50
    And I see the organisation state as "PENDING"
    When I select approve organisation
    Then I am on confirm decision page
15:25:46 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(xpath, //button[contains(text(),"Confirm")])
15:25:46 GMT+0100 (British Summer Time) : wait done for sec50
15:25:46 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-summary-list__key)
15:25:46 GMT+0100 (British Summer Time) : wait done for sec50
    When I confirm the decision
    Then I get a registration confirmation
15:25:46 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .hmcts-banner__message)
15:25:48 GMT+0100 (British Summer Time) : wait done for sec50
    When I select "Active organisations" tab
    And I search for the organisation
    Then I can see the orgainsation listed
15:26:34 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-table tr)
15:26:34 GMT+0100 (British Summer Time) : wait done for sec50
    When I click first organization view link
15:26:34 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-table tr)
15:26:34 GMT+0100 (British Summer Time) : wait done for sec50
    Then I see "Organisation details" on organisation details page
15:26:35 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, #content app-org-details-info h1)
15:26:36 GMT+0100 (British Summer Time) : wait done for sec50
15:26:36 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, .govuk-summary-list__key)
15:26:36 GMT+0100 (British Summer Time) : wait done for sec50
    And I see the organisation state as "ACTIVE"

@2.0_test
Feature: Login

  @2.0_test @fullfunctional
  Scenario: un-authenticated user login
    When I navigate to EUI Approve Organisation Url
15:26:38 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:26:39 GMT+0100 (British Summer Time) : wait done for sec50
15:26:39 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:26:39 GMT+0100 (British Summer Time) : wait done for sec50
    Then I am on Idam login page
    When I enter an Invalid email-address and password to login
    Then I should be redirected to the Idam login page
15:26:39 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, h1.heading-large)
15:26:40 GMT+0100 (British Summer Time) : wait done for sec50
    Then I should see failure error summary

  @2.0_test
  Scenario: login and log out from approve organisation as HMCTS Admin user
    When I navigate to EUI Approve Organisation Url
15:26:41 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:26:42 GMT+0100 (British Summer Time) : wait done for sec50
15:26:42 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:26:42 GMT+0100 (British Summer Time) : wait done for sec50
    Given I am logged into approve organisation with HMCTS admin
15:26:42 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:26:42 GMT+0100 (British Summer Time) : wait done for sec50
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 2
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 2
    Then I should be redirected to approve organisation dashboard page
15:26:48 GMT+0100 (British Summer Time) : Started step
15:26:54 GMT+0100 (British Summer Time) : browser readyState value  "complete"
15:26:54 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(xpath, //a[@class='hmcts-header__link'])
15:26:54 GMT+0100 (British Summer Time) : wait done for sec50
    When I select the sign out link
    Then I should be redirected to the Idam login page
15:27:08 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, h1.heading-large)
15:27:08 GMT+0100 (British Summer Time) : wait done for sec50

  @2.0_test
  Scenario: login and log out from approve organisation as FR user
    When I navigate to EUI Approve Organisation Url
15:27:09 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:27:10 GMT+0100 (British Summer Time) : wait done for sec50
15:27:10 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:27:10 GMT+0100 (British Summer Time) : wait done for sec50
    Given I am logged into approve organisation with FR judge details
15:27:10 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:27:10 GMT+0100 (British Summer Time) : wait done for sec50
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 3
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 3
    Then I should be redirected to approve organisation dashboard page
15:27:12 GMT+0100 (British Summer Time) : Started step
15:27:18 GMT+0100 (British Summer Time) : browser readyState value  "complete"
15:27:18 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(xpath, //a[@class='hmcts-header__link'])
15:27:18 GMT+0100 (British Summer Time) : wait done for sec50
    When I select the sign out link
    Then I should be redirected to the Idam login page
15:27:31 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, h1.heading-large)
15:27:31 GMT+0100 (British Summer Time) : wait done for sec50

  @2.0_test @fullfunctional
  Scenario: Verify the direct link navigate to login page
    When I navigate to EUI Approve Organisation Url
15:27:32 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:27:33 GMT+0100 (British Summer Time) : wait done for sec50
15:27:33 GMT+0100 (British Summer Time) : Before starting wait for element 50 : By(css selector, input#username)
15:27:33 GMT+0100 (British Summer Time) : wait done for sec50
    Given I navigate to approve organisation Url direct link
    Then I should be redirected back to Login page after direct link

5 scenarios (5 passed)
35 steps (35 passed)
2m34.690s


=====================================================================================
    Multiple Cucumber HTML report generated in:

    /Users/rohithtiru/workspace/solirius/repos/rpx-xui-approve-org/reports/tests/smoke/index.html
=====================================================================================

[15:27:59] I/launcher - 0 instance(s) of WebDriver still running
[15:27:59] I/launcher - chrome #01 passed
✨  Done in 160.16s.

### CODE REVIEW

**Review by Vamshi-Muniganti — DISMISSED** [review]
looks good

**Review by sreekanthpuligadda — DISMISSED** [review]
LGTM

**Review by sreekanthpuligadda — APPROVED** [review]

**Review by Vamshi-Muniganti — APPROVED** [review]
looks ok to me

**Review by sreekanthpuligadda — DISMISSED** [review]

**Review by Vamshi-Muniganti — APPROVED** [review]
looks good

**Pull request closed without merging**
